# Generated by Django 2.0.2 on 2018-05-11 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artpiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('medium', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='uploads/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='artpiece',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.Locations'),
        ),
    ]
