# Generated by Django 2.0.2 on 2018-05-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='location',
        ),
    ]
