# Generated by Django 2.0.2 on 2018-05-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_remove_artpiece_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='webContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='image',
            field=models.FileField(upload_to='uploads/', verbose_name='Image File'),
        ),
    ]
