# Generated by Django 2.0.2 on 2018-05-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_webcontent_propertyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='medium',
            field=models.CharField(choices=[('drawing', 'Drawings'), ('paint', 'Paintings'), ('digital', 'Digital Artwork')], default='drawing', max_length=10),
        ),
    ]
