# Generated by Django 2.0.2 on 2018-05-30 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20180529_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='date created'),
        ),
    ]
